codecov: true
language: java
jdk:
  - openjdk14

sudo: false # faster builds

services:
  - postgresql

before_install:
  - psql -c 'create database aggregator;' -U postgres

after_success:
  - bash <(curl -s https://codecov.io/bash)